zenfone9: Move prebuilt modules into extra vendor_dlkm list
We need to load this modules only on second stage, not on BOOT_KERNEL_MODULES.
Else, build fail with tntfs.ko

ERROR: tntfs.ko from BOOT_KERNEL_MODULES was not found

Change-Id: Ie857729f34e96ff964dfb7fb6bc9f23493a12380
Signed-off-by: micky387 <mickaelsaibi@free.fr>